### Зчитати WEB сторінку з сайту https://www.formula1.com/en/drivers.html

### Необхідно створити data.frame «formula1» з наступними даними: Biography, Team, Country, Podiums, Points, Grands Prix entered, World Championships, Highest race finish, Highest grid position, Date of birth, Place of birth.

In [1]:
import requests
from requests import get
from bs4 import BeautifulSoup
import numpy as np
import urllib3

from time import sleep
from random import randint

from selenium import webdriver
links =[]
pages = np.arange(1, 2,1)
http = urllib3.PoolManager()

In [15]:
for page in pages:
    page = http.request('GET','https://www.formula1.com/en/drivers.html')
    soup = BeautifulSoup(page.data, 'html.parser')
    # parts of links are stored here:
    links_href = soup.find_all('a', class_="listing-item--link",href =True)

   
    
    for link1 in links_href:
        # Put it together:
        name1 = 'https://www.formula1.com'+link1.get('href')
        print(name1)
        links.append(name1)

https://www.formula1.com/en/drivers/lewis-hamilton.html
https://www.formula1.com/en/drivers/max-verstappen.html
https://www.formula1.com/en/drivers/valtteri-bottas.html
https://www.formula1.com/en/drivers/lando-norris.html
https://www.formula1.com/en/drivers/charles-leclerc.html
https://www.formula1.com/en/drivers/sergio-perez.html
https://www.formula1.com/en/drivers/daniel-ricciardo.html
https://www.formula1.com/en/drivers/carlos-sainz.html
https://www.formula1.com/en/drivers/esteban-ocon.html
https://www.formula1.com/en/drivers/pierre-gasly.html
https://www.formula1.com/en/drivers/lance-stroll.html
https://www.formula1.com/en/drivers/fernando-alonso.html
https://www.formula1.com/en/drivers/yuki-tsunoda.html
https://www.formula1.com/en/drivers/kimi-raikkonen.html
https://www.formula1.com/en/drivers/antonio-giovinazzi.html
https://www.formula1.com/en/drivers/sebastian-vettel.html
https://www.formula1.com/en/drivers/george-russell.html
https://www.formula1.com/en/drivers/mick-schumacher.html
https://www.formula1.com/en/drivers/nicholas-latifi.html
https://www.formula1.com/en/drivers/nikita-mazepin.html

In [41]:
formula1_list = []

for i in range(len(links)):
    i = http.request('GET', links[i])
    soup = BeautifulSoup(i.data, 'html.parser')
    name =[]
    biography = []
    info_d = []
    man_h1 = soup.find_all('h1', class_="driver-name")
    time_ = soup.find_all('td',class_="stat-value")
    bio = soup.find_all('div',class_="text parbase")
    
    for link2 in man_h1:
        name2 = link2.get_text()
        name.append(name2)
    
    for link3 in time_:
        name3 = link3.get_text()
        info_d.append(name3)
        
    for link4 in bio:
        name4 = link4.get_text()
        info_d.append(name3)   
        
    formula1_list.append(name + [" ".join(biography)] + info_d[0:10])

In [42]:
formula1 = pd.DataFrame(formula1_list, columns =['Name','Biography', 'Team', 'Country', 'Podiums', 'Points', 'Grands Prix entered', 
                                                 'World Championships', 'Highest race finish', 'Highest grid position', 
                                                 'Date of birth', 'Place of birth'])
formula1

,Name,Biography,Team,Country,Podiums,Points,Grands Prix entered,World Championships,Highest race finish,Highest grid position,Date of birth,Place of birth
0,Lewis Hamilton,,Mercedes,United Kingdom,169,3872,270,7,1 (x98),1,07/01/1985,"Stevenage, England"
1,Max Verstappen,,Red Bull Racing,Netherlands,46,1242,123,N/A,1 (x11),1,30/09/1997,"Hasselt, Belgium"
2,Valtteri Bottas,,Mercedes,Finland,59,1559,161,N/A,1 (x9),1,28/08/1989,"Nastola, Finland"
3,Lando Norris,,McLaren,United Kingdom,2,187,42,N/A,3 (x2),3,13/11/1999,"Bristol, England"
4,Charles Leclerc,,Ferrari,Monaco,12,441,63,N/A,1 (x2),1,16/10/1997,"Monte Carlo, Monaco"
5,Sergio Perez,,Red Bull Racing,Mexico,10,738,197,N/A,1 (x1),2,26/01/1990,"Guadalajara, Mexico"
6,Daniel Ricciardo,,McLaren,Australia,31,1183,192,N/A,1 (x7),1,01/07/1989,"Perth, Australia"
7,Carlos Sainz,,Ferrari,Spain,2,392,123,N/A,2 (x1),3,01/09/1994,"Madrid, Spain"
8,Esteban Ocon,,Alpine,France,1,208,71,N/A,2 (x1),3,17/09/1996,"Évreux, Normandy"
9,Pierre Gasly,,AlphaTauri,France,2,207,68,N/A,1 (x1),4,07/02/1996,"Rouen, France"
10,Lance Stroll,,Aston Martin,Canada,3,147,82,N/A,3 (x3),1,29/10/1998,"Montreal, Canada"
11,Fernando Alonso,,Alpine,Spain,97,1904,318,2,1 (x32),1,29/07/1981,"Oviedo, Spain"
12,Yuki Tsunoda,,AlphaTauri,Japan,N/A,2,4,N/A,9 (x1),13,11/05/2000,"Sagamihara, Japan"
13,Kimi Räikkönen,,Alfa Romeo Racing,Finland,103,1863,336,1,1 (x21),1,17/10/1979,"Espoo, Finland"
14,Antonio Giovinazzi,,Alfa Romeo Racing,Italy,N/A,18,44,N/A,5 (x1),7,14/12/1993,"Martina Franca, Italy"
15,Sebastian Vettel,,Aston Martin,Germany,121,3018,262,4,1 (x53),1,03/07/1987,"Heppenheim, Germany"
16,George Russell,,Williams,United Kingdom,N/A,3,42,N/A,9 (x1),2,15/02/1998,"King's Lynn, England"
17,Mick Schumacher,,Haas F1 Team,Germany,N/A,0,4,N/A,16 (x2),18,22/03/1999,"Vufflens-le-Château, Switzerland"
18,Nicholas Latifi,,Williams,Canada,N/A,0,21,N/A,11 (x3),14,29/06/1995,"Montreal, Canada"
19,Nikita Mazepin,,Haas F1 Team,Russian Automobile Federation,N/A,0,4,N/A,17 (x1),19,02/03/1999,"Moscow, Russia"

### 1. Виведіть гонщиків перші 10 гонщиків дата фрейму.

In [35]:
formula1.head(10)

,Name,Biography,Team,Country,Podiums,Points,Grands Prix entered,World Championships,Highest race finish,Highest grid position,Date of birth,Place of birth,1,2,3
0,Lewis Hamilton,,Mercedes,United Kingdom,169,3872,270,7,1 (x98),1,07/01/1985,"Stevenage, England","Stevenage, England","Stevenage, England","Stevenage, England"
1,Max Verstappen,,Red Bull Racing,Netherlands,46,1242,123,N/A,1 (x11),1,30/09/1997,"Hasselt, Belgium","Hasselt, Belgium","Hasselt, Belgium","Hasselt, Belgium"
2,Valtteri Bottas,,Mercedes,Finland,59,1559,161,N/A,1 (x9),1,28/08/1989,"Nastola, Finland","Nastola, Finland","Nastola, Finland","Nastola, Finland"
3,Lando Norris,,McLaren,United Kingdom,2,187,42,N/A,3 (x2),3,13/11/1999,"Bristol, England","Bristol, England","Bristol, England","Bristol, England"
4,Charles Leclerc,,Ferrari,Monaco,12,441,63,N/A,1 (x2),1,16/10/1997,"Monte Carlo, Monaco","Monte Carlo, Monaco","Monte Carlo, Monaco","Monte Carlo, Monaco"
5,Sergio Perez,,Red Bull Racing,Mexico,10,738,197,N/A,1 (x1),2,26/01/1990,"Guadalajara, Mexico","Guadalajara, Mexico","Guadalajara, Mexico","Guadalajara, Mexico"
6,Daniel Ricciardo,,McLaren,Australia,31,1183,192,N/A,1 (x7),1,01/07/1989,"Perth, Australia","Perth, Australia","Perth, Australia","Perth, Australia"
7,Carlos Sainz,,Ferrari,Spain,2,392,123,N/A,2 (x1),3,01/09/1994,"Madrid, Spain","Madrid, Spain","Madrid, Spain","Madrid, Spain"
8,Esteban Ocon,,Alpine,France,1,208,71,N/A,2 (x1),3,17/09/1996,"Évreux, Normandy","Évreux, Normandy","Évreux, Normandy","Évreux, Normandy"
9,Pierre Gasly,,AlphaTauri,France,2,207,68,N/A,1 (x1),4,07/02/1996,"Rouen, France","Rouen, France","Rouen, France","Rouen, France"

### 2. Виведіть всх гонщиків із США.

In [36]:
formula1[formula1.Country == 'USA']

Empty DataFrame
Columns: [Name, Biography, Team, Country, Podiums, Points, Grands Prix entered, World Championships, Highest race finish, Highest grid position, Date of birth, Place of birth, 1, 2, 3]
Index: []

### 3. Скільки гонщиків брали участь у «Чемпіонаті світу».

In [37]:
len(formula1[formula1['World Championships'] != "N/A"])

4